#!/usr/bin/env bash
# Seed dev-only backend/.env + google-credentials.json for the live uvicorn path.
# Idempotent: only writes files that are missing. All values are local-dev
# placeholders — no real credentials. The hermetic E2E harness does NOT use these.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$REPO_ROOT/backend"
cd "$BACKEND_DIR"

# Firestore emulator host/port must match firebase.json (repo root).
FIRESTORE_PORT="$(python3 - <<'PY'
import json, pathlib
cfg = json.loads(pathlib.Path("../firebase.json").read_text())
print(cfg.get("emulators", {}).get("firestore", {}).get("port", 8085))
PY
)"

if [ ! -f google-credentials.json ]; then
  echo "generating dev google-credentials.json (syntactically valid SA, generated RSA key)"
  TMP_KEY="$(mktemp)"
  openssl genrsa -out "$TMP_KEY" 2048 2>/dev/null
  PRIVATE_KEY_JSON="$(python3 - "$TMP_KEY" <<'PY'
import json, sys
print(json.dumps(open(sys.argv[1]).read()))
PY
)"
  cat > google-credentials.json <<EOF
{
  "type": "service_account",
  "project_id": "demo-omi",
  "private_key_id": "dev-local-key",
  "private_key": ${PRIVATE_KEY_JSON},
  "client_email": "dev-local@demo-omi.iam.gserviceaccount.com",
  "client_id": "000000000000000000000",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/dev-local%40demo-omi.iam.gserviceaccount.com"
}
EOF
  rm -f "$TMP_KEY"
else
  echo "google-credentials.json already present"
fi

if [ ! -f .env ]; then
  echo "generating dev backend/.env (local emulator path)"
  cat > .env <<EOF
# Dev-only local backend env for the live uvicorn path on the Cloud Agent VM.
# Generated by .cursor/seed-backend-env.sh — NOT for production. No real secrets.
LOCAL_DEVELOPMENT=true
ADMIN_KEY=local_dev_admin_key
ADMIN_KEY_AUTH_ENABLED=true

# Enable the universal-memory product path for local dev so /v3/memories
# create/read round-trips (production fail-closes to off until rollout proof).
MEMORY_ENABLED=on

# Firestore emulator (started by .cursor/start.sh); pins project + host.
GOOGLE_CLOUD_PROJECT=demo-omi
FIREBASE_PROJECT_ID=demo-omi
FIREBASE_AUTH_PROJECT_ID=demo-omi
FIRESTORE_EMULATOR_HOST=127.0.0.1:${FIRESTORE_PORT}
GOOGLE_APPLICATION_CREDENTIALS=google-credentials.json

# Local Redis (started by .cursor/start.sh).
REDIS_DB_HOST=127.0.0.1
REDIS_DB_PORT=6379
REDIS_DB_PASSWORD=

# Required for encryption of conversations/memories/chat at rest.
ENCRYPTION_SECRET=local_dev_encryption_secret_change_me_0123456789abcdef

# Placeholder provider keys — real external calls fail at call time by design.
OPENAI_API_KEY=sk-local-dev-placeholder
TYPESENSE_HOST=localhost
TYPESENSE_HOST_PORT=8108
TYPESENSE_API_KEY=local-dev-typesense

# Pinecone intentionally unset -> database/vector_db.py takes its no-op path.
PINECONE_API_KEY=
PINECONE_INDEX_NAME=
EOF
else
  echo "backend/.env already present"
fi

echo "backend env seeded (firestore emulator port ${FIRESTORE_PORT})"
